export const SETACT = 'SETACT';
export const SETCHATBOTACT = 'SETCHATBOTACT';
export const SETWCAG = 'SETWCAG';
export const SETCHATBOTWCAG = 'SETCHATBOTWCAG';
export const SETCSS = 'SETCSS';
export const SETCUI = 'SETCUI';
export const SETCHATBOTCUI = 'SETCHATBOTCUI';
export const SETSUMMARY = 'SETSUMMARY';
export const SETCHATBOTSUMMARY = 'SETCHATBOTSUMMARY';
export const SETEVAL = 'SETEVAL';
export const SETFILTER = 'SETFILTER';
export const SETALLFILTER = 'SETALLFILTER';
export const SETRESULTFILTER = 'SETRESULTFILTER';
export const SETALLRESULTFILTER = 'SETALLRESULTFILTER';
export const SETCURRENTRULE = 'SETCURRENTRULE';
export const SETCURRENTRULERESULTS = 'SETCURRENTRULERESULTS';
export const SETHIGHLIGHTACTIVE = 'SETHIGHLIGHTACTIVE';
export const RESET = 'RESET';

export const SETDETECTINGCHATBOT = 'SETDETECTINGCHATBOT';
export const SETEVALUATECHATBOT = 'SETEVALUATECHATBOT';
export const SETURL = 'SETURL';
export const SETSELECTORS = 'SETSELECTORS';

export const SETINTERACTIONINITIALIZED = 'SETINTERACTIONINITIALIZED';
export const SETTABID = 'SETTABID';
export const SETSELECTORSDETECTED = 'SETSELECTORSDETECTED';
export const SETSIDEPANELURL = 'SETSIDEPANELURL';
