import { MessageResponse, STATUS } from '../../messaging/message-types';
import { ERROR_CLASS_NAME_CONTENT } from './errors.class.content';

type ContentErrorNames = (typeof ERROR_CLASS_NAME_CONTENT)[keyof typeof ERROR_CLASS_NAME_CONTENT];
const error = (
  code: (typeof ERROR_CLASS_NAME_CONTENT)[keyof typeof ERROR_CLASS_NAME_CONTENT],
  message: string,
): MessageResponse => ({ status: STATUS.ERROR, code, message });

export const ERROR_MESSAGES_CONTENT: Record<ContentErrorNames, MessageResponse> = {
  [ERROR_CLASS_NAME_CONTENT.ACTION_DOES_NOT_EXIST_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.ACTION_DOES_NOT_EXIST_ERROR,
    'The requested action does not exist.',
  ),
  [ERROR_CLASS_NAME_CONTENT.IFRAME_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.IFRAME_NOT_FOUND_ERROR,
    'Chatbot iframe not found on the page.',
  ),
  [ERROR_CLASS_NAME_CONTENT.INPUT_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.INPUT_NOT_FOUND_ERROR,
    'Chatbot input field not found on the page.',
  ),
  [ERROR_CLASS_NAME_CONTENT.MICROPHONE_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.MICROPHONE_NOT_FOUND_ERROR,
    'Chatbot microphone element not found on the page.',
  ),
  [ERROR_CLASS_NAME_CONTENT.DIALOG_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.DIALOG_NOT_FOUND_ERROR,
    'Chatbot message dialog container not found on the page.',
  ),
  [ERROR_CLASS_NAME_CONTENT.WINDOW_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.WINDOW_NOT_FOUND_ERROR,
    'Chatbot main window container not found on the page.',
  ),
  [ERROR_CLASS_NAME_CONTENT.SELECTORS_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.SELECTORS_NOT_FOUND_ERROR,
    'Chatbot selectors not found or invalid.',
  ),
  [ERROR_CLASS_NAME_CONTENT.INTERACTION_IN_PROGRESS_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.INTERACTION_IN_PROGRESS_ERROR,
    'An interaction is already in progress. Please wait for it to complete.',
  ),
  [ERROR_CLASS_NAME_CONTENT.UNKNOWN_CONTENT_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.UNKNOWN_CONTENT_ERROR,
    'An unknown error occurred in the content script.',
  ),
  [ERROR_CLASS_NAME_CONTENT.ELEMENT_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.ELEMENT_NOT_FOUND_ERROR,
    'No relevant element was found on the page.',
  ),
  [ERROR_CLASS_NAME_CONTENT.CANCELLATION_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.CANCELLATION_ERROR,
    'The operation was cancelled by the user.',
  ),
  [ERROR_CLASS_NAME_CONTENT.OBSERVER_FOUND_NO_MESSAGES_AFTER_RETRY_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.OBSERVER_FOUND_NO_MESSAGES_AFTER_RETRY_ERROR,
    'The observer found no messages after retrying.',
  ),
  [ERROR_CLASS_NAME_CONTENT.IFRAME_NOT_ACCESSIBLE_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.IFRAME_NOT_ACCESSIBLE_ERROR,
    'The chatbot iframe is not accessible due to cross-origin restrictions.',
  ),
  [ERROR_CLASS_NAME_CONTENT.VOICE_INPUT_FAILED_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.VOICE_INPUT_FAILED_ERROR,
    'Voice input failed. Please check your microphone settings.',
  ),
  [ERROR_CLASS_NAME_CONTENT.MESSAGE_SELECTOR_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.MESSAGE_SELECTOR_NOT_FOUND_ERROR,
    'Message selector not found on the page.',
  ),
  [ERROR_CLASS_NAME_CONTENT.CHATBOT_BASE_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.CHATBOT_BASE_ERROR,
    'A base chatbot error occurred.',
  ),
  [ERROR_CLASS_NAME_CONTENT.ELEMENT_MANUAL_SELECTION_IN_PROGRESS_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.ELEMENT_MANUAL_SELECTION_IN_PROGRESS_ERROR,
    'Element manual selection is already in progress.',
  ),
  [ERROR_CLASS_NAME_CONTENT.OBSERVER_RESPONSE_DETECTION_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.OBSERVER_RESPONSE_DETECTION_ERROR,
    'Failed to detect response from the observer.',
  ),
  [ERROR_CLASS_NAME_CONTENT.FAILED_TO_SEND_VOICE_MESSAGE_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.FAILED_TO_SEND_VOICE_MESSAGE_ERROR,
    'Failed to send voice message.',
  ),
  [ERROR_CLASS_NAME_CONTENT.MESSAGE_INSERTION_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.MESSAGE_INSERTION_ERROR,
    'Failed to insert message.',
  ),
  [ERROR_CLASS_NAME_CONTENT.CHATBOT_NOT_DETECTED_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.CHATBOT_NOT_DETECTED_ERROR,
    'Chatbot was not detected on the page.',
  ),
  [ERROR_CLASS_NAME_CONTENT.NO_INTERACTION_IN_PROGRESS_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.NO_INTERACTION_IN_PROGRESS_ERROR,
    'No interaction is currently in progress.',
  ),
  [ERROR_CLASS_NAME_CONTENT.NO_ELEMENT_VERIFICATION_IN_PROGRESS_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.NO_ELEMENT_VERIFICATION_IN_PROGRESS_ERROR,
    'No element verification is currently in progress.',
  ),
  [ERROR_CLASS_NAME_CONTENT.INVALID_SELECTOR_PROVIDED_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.INVALID_SELECTOR_PROVIDED_ERROR,
    'Invalid selector provided.',
  ),
  [ERROR_CLASS_NAME_CONTENT.WCAG_EVALUATION_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.WCAG_EVALUATION_ERROR,
    'WCAG evaluation failed.',
  ),
  [ERROR_CLASS_NAME_CONTENT.ACT_EVALUATION_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.ACT_EVALUATION_ERROR,
    'ACT evaluation failed.',
  ),
  [ERROR_CLASS_NAME_CONTENT.CUI_EVALUATION_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.CUI_EVALUATION_ERROR,
    'CUI evaluation failed.',
  ),
  [ERROR_CLASS_NAME_CONTENT.INSTANCE_NOT_INITIALIZED_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.INSTANCE_NOT_INITIALIZED_ERROR,
    'Instance was not initialized.',
  ),
  [ERROR_CLASS_NAME_CONTENT.SETTINGS_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.SETTINGS_NOT_FOUND_ERROR,
    'Settings not found.',
  ),
  [ERROR_CLASS_NAME_CONTENT.API_KEY_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.API_KEY_NOT_FOUND_ERROR,
    'API key not found.',
  ),
  [ERROR_CLASS_NAME_CONTENT.LOCALE_NOT_FOUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.LOCALE_NOT_FOUND_ERROR,
    'Locale not found.',
  ),
  [ERROR_CLASS_NAME_CONTENT.PORT_CONNECTION_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.PORT_CONNECTION_ERROR,
    'Failed to establish port connection.',
  ),
  [ERROR_CLASS_NAME_CONTENT.PORT_INITIAL_CONFIGURATION_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.PORT_INITIAL_CONFIGURATION_ERROR,
    'Failed to configure port initially.',
  ),
  [ERROR_CLASS_NAME_CONTENT.FAILED_COMMUNICATION_WITH_BACKGROUND_ERROR]: error(
    ERROR_CLASS_NAME_CONTENT.FAILED_COMMUNICATION_WITH_BACKGROUND_ERROR,
    'Failed to communicate with background script.',
  ),
};
